base_url = "https://ac-room.org"
title = "筑波大学情報科学類産学間連携推進室"
description = ""

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]
nav = [
  { title = "トップ", path = "/" },
  { title = "メンバー", path = "/members/" },
  { title = "お知らせ", path = "/news/" },
  { title = "成果報告", path = "/publication/" },
  { title = "プロジェクト", path = "/projects/" },
  { title = "弊室について", path = "/about/" },
]
